defaults:
  - base
  - model: ???
  - _self_
  - prompts: null

# tag: ''
run_type: learn_delta

max_steps: 1000
batch_size: 1
grad_accum_steps: 10
scale_batch_size: 4
scale_range: [.1, 5]
randomize_scale_sign: true

optim_class: torch.optim.AdamW
optim_params:
  lr: 0.1
  betas: [0.5, 0.8]
  weight_decay: 0.333

ckpt_logging_freq: 100
init_from_ckpt: null

model:
  compile: true

base_sample_settings:
  guidance_scale: 7.5
